### ISSUE TITLE
Blank Store Development

### ISSUE THREAD

**Issue by jw243** [mar-v-in/BlankStore#15]
I am glad that there is Blank Store, that way I can install free apps on my google-free phone. I would really like to see the app developed further. It would be great if the following features could be included:

- show individual app ratings and comments as well as suggested and similar apps.
- show apps I have already purchased.
- option to purchase apps.
- include framework to make apps work that check whether an app has been purchased correctly.

Best regards.

**Comment by mar-v-in** [comment]
BlankStore was discontinued.

It is intended to provide a new free software Play Store client, based on new Play Store APIs (BlankStore uses legacy APIs) as part of the microG project.

**Comment by jw243** [comment]
That sounds very interesting. When is the new Play Store client expected to replace blank store? Where would I find it?

**Comment by aphirst** [comment]
I can only imagine that that's simply currently "on the cards", and am under the impression that other microg functionality is being prioritised. Perhaps in the (unfortunate, but possible) event that BlankStore stops working outright, the priority would change. But BlankStore works pretty well for most cases, so I think we all just have to wait patiently.
