### ISSUE TITLE
BlankStore crashes on any operation

### ISSUE THREAD

**Issue by goncalopp** [mar-v-in/BlankStore#16]
It seems to be looking for apps that are not (or have ever been) on my device. 
I've had it working before on this device on a different account

Here's the relevant logcat sections:

> 06-15 21:23:33.196 12764 12788 D DefaultGooglePlay: queryeAppList: gggg[DONE]
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime: Process: com.android.vending, PID: 12764
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime: Theme: themes:{}
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:309)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime: Caused by: java.lang.RuntimeException: could not init /storage/emulated/0/.nogapps/blankstore/com.hbg.crazysurgery.surgerysimulator.heart.doctor.games!
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at com.android.vending.google.GooglePlayConnection.makeDirectoryReady(GooglePlayConnection.java:103)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at com.android.vending.google.DefaultGooglePlayConnection.queryImage(DefaultGooglePlayConnection.java:262)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at com.android.vending.tasks.ImageToViewTask.doInBackground(ImageToViewTask.java:42)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at com.android.vending.tasks.ImageToViewTask.doInBackground(ImageToViewTask.java:13)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:295)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 06-15 21:23:33.221 12764 12807 E AndroidRuntime:        ... 4 more

**Comment by ArchangeGabriel** [comment]
Have you had a look at https://github.com/mar-v-in/BlankStore/issues/13?

**Comment by goncalopp** [comment]
I hadn't, and I can confirm giving storage permissions fixes the issue. 
Closing this one, thanks!
